#!/usr/bin/env bash
# Install nginx on your web-01

sudo apt-get update -y
sudo apt-get install -y nginx

sudo ufw allow 'Nginx HTTP'

sudo echo "Hello World!" | sudo /var/www/index.html

sudo service nginx restart
