#!/usr/bin/env bash
# Install nginx on your web-01

apt-get update
apt-get install -y nginx

echo "Hello World!" > /usr/share/nginx/html/index.html

service nginx restart

echo "Nginx installed and configured successfully."
