#!/usr/bin/env bash
# Install nginx on your web-01

apt-get update -y
apt-get install -y nginx

ufw allow 'Nginx HTTP'

echo "Hello World!" > /var/www/index.nginx.html

service nginx start

echo "Nginx installed and configured successfully."
