#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page

# Update package index and install Nginx
sudo apt-get -y update
sudo apt-get -y install nginx

# Allow Nginx through firewall
sudo ufw allow 'Nginx HTTP'

# Create index file with "Hello World" nessage
echo "Hello World" | sudo tee /var/www/html/index.html

# Configure redirection in Nginx
sudo sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/ permanent; }' /etc/nginx/sites-available/default

# Restart Nginx to apply changes
sudo systemct1 nginx restart
