#!/usr/bin/env bash
# Update package index and install Nginx
sudo apt-get update -y
sudo apt-get install -y nginx

# Create custom 404 page HTML file
sudo bash - c 'echo "Ceci n'"'"'est pas une page" | sudo tee /var/www/html/404.html'

# Configure Nginx to use custom 404 page
sudo bash -c 'cat > /etc/nginx/sites-available/default' <<EOF
server {
   listen 80 default_server;
   listen [::]:80 default_server;

   root /var/www/html;
   index index.html;

   location /redirect_me {
      return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
   }

   error_page 404 /404.html;
   location = /404.html {
      internal;
   }
}
EOF

# Restart Nginx to apply the changes
sudo systemctl restart nginx
