#!/usr/bin/env bash

# Update package index and install Nginx
sudo apt-get -y update
sudo apt-get -y install nginx

# Create custom 404 page file
echo "<!DOCTYPE html><html><head><title>404 Not Found</title></head><body><h1>Ceci n'est pas une page</h1></body></html>" | sudo tee /var/www/html/404.html

# Configure Nginx to use custom 404 page
sudo bash -c 'cat > /etc/nginx/sites-available/default' << EOF
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm;

    server_name _;

    location / {
        try_files \$uri \$uri/ =404;
    }

    error_page 404 /404.html;
    location = /404.html {
        internal;
    }
}
EOF

# Restart Nginx to apply changes
sudo service nginx restart
