#!/usr/bin/env bash
# Install nginx
apt-get -y update
apt-get -y install nginx

# set up custom HTTP response header
echo'add_header X-Served-By $HOSTNAME;' >> /etc/nginx/sites-availlable/default

# restart nginx to apply changes
sudo service nginx restart
