#!/usr/bin/env bash
# configures a server to listen on port 80
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx start
curl 0:80
service nginx status | grep "nginx is not running"
