#!/usr/bin/env bash
# configures a server to listen on port 80
sed -i 's/listen\s*80;/listen 80;/g' /etc/nginx/sites-available/default

# start Nginx service
service nginx start
kill "$(pgrep 'nginx' | head -1)"
