#!/usr/bin/env bash
# # Function to handle SIGTERM and SIGQUIT signals

cleanup() {
    echo "I hate the kill command"
    rm -f /var/run/myscript.pid
    exit 0
}

interrupt() {
    echo "Y U no love me?!"
}

trap 'cleanup' SIGTERM SIGQUIT

trap 'interrupt' SIGINT

echo $$ > /var/run/myscript.pid

while true; do
    echo "To infinity and beyond"
    sleep 1
done
