#!/usr/bin/env bash
# manages manage_my_process

start() {
	./manage_my_process &
	echo $! > /var/run/my_process.pid
	echo "manage_my_process started"
}

stop() {
    if [ -f /var/run/my_process.pid ]; then
	pid=$(cat /var/run/my_process.pid)
	sudo kill $pid
	rm -f /var/run/my_process.pid
	echo "manage_my_process stopped"
    else
	echo "manage_my_process is not running"
    fi
}

restart() {
    stop
    start
    echo "manage_my_process restarted"
}

case "$1" in
    start)
	start
	;;
    stop)
	stop
	;;
    restart)
	restart
	;;
    *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
	;;
esac

exit 0
