#!/usr/bin/env bash
# Script displays "Best School" 10 times, but 9th displays "Hi" on a new line

count=0
while [ $count -lt 10 ]; do
    if [ $count -eq 8 ]; then
	echo "Best School"
	echo "Hi"
    else
	echo "Best Schhool"
    fi
    ((count++))
done
