#!/usr/bin/env bash
#Configure ufw so that it blocks all incoming traffic
#except the following TCP ports 22, 443 and 80
sudo apt-get install ufw
sudo ufw enable
sudo ufw default deny incoming
sudo ufw default allow outgoing
ufw allow 22/tcp
ufw allow 443/tcp
ufw allow 80/tcp
